version: '3.8'

services:
  polytech:
    build: ./polytech
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@polytech-db:5432/polytech
    depends_on:
      - polytech-db
    restart: always

  polytech-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=polytech
    volumes:
      - polytech-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  erasmumu:
    build: ./erasmumu
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=mongodb://erasmumu-db:27017
    depends_on:
      - erasmumu-db
    restart: always

  erasmumu-db:
    image: mongo:6-jammy
    restart: always
    volumes:
      - erasmumu-db-data:/data/db
    ports:
      - "27018:27017"

  mi8:
    build: ./mi8
    ports:
      - "50051:50051"
    restart: always

volumes:
  polytech-db-data:
  erasmumu-db-data:
